language: node_js
node_js:
   - "12"
   - "10"
   - "8"

script:
   - grunt standards
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
